apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busapp
  template:
    metadata:
      labels:
        app: busapp
    spec:
      containers:
        - name: busapp
          image: your-docker-image:tag
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: busapp-service
spec:
  type: LoadBalancer
  selector:
    app: busapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
